workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 40
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local build version
        script: |
          cd apps/enmeshed
          sed -i.bak 's/^version:.*$/version: 1.0.0+1/' pubspec.yaml

      - name: Install melos
        script: dart pub global activate melos

      - name: Bootstrap repository
        script: melos bootstrap

      - name: Pod install
        script: |
          cd apps/enmeshed/ios
          pod install

      - name: Create export options plist and build ipa
        script: |
          cd apps/enmeshed
          
          # Create export options plist in the current directory
          cat > export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
          
          # Build IPA using the local export options file
          flutter build ipa \
            --export-options-plist=export_options.plist \
            --dart-define="app_baseUrl=$app_baseUrl" \
            --dart-define="app_clientId=$app_clientId" \
            --dart-define="app_clientSecret=$app_clientSecret"

    artifacts:
      - apps/enmeshed/build/ios/ipa/*.ipa