workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 40
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local build version
        script: |
          cd apps/enmeshed
          # Set a dummy version for development
          echo "version: 1.0.0+1" >> pubspec.yaml

      - name: Install melos
        script: dart pub global activate melos

      - name: Bootstrap repository
        script: melos bootstrap

      - name: Pod install
        script: |
          cd apps/enmeshed/ios
          pod install

      - name: Flutter build ipa
        script: |
          cd apps/enmeshed
          flutter build ipa \
            --no-codesign \
            --dart-define="app_baseUrl=$app_baseUrl" \
            --dart-define="app_clientId=$app_clientId" \
            --dart-define="app_clientSecret=$app_clientSecret"

    artifacts:
      - apps/enmeshed/build/ios/ipa/*.ipa