workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 40
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "enmeshed-v+([0-9]).+([0-9]).+([0-9])"
          include: true
      cancel_previous_builds: true
    environment:
      groups:
        - config-secrets
        - webhook-secrets
      ios_signing:
        distribution_type: app_store
        bundle_identifier: eu.enmeshed.app
      flutter: stable
      xcode: 16.0
      cocoapods: default
    scripts:
#      - name: Set up code signing settings on Xcode project
#        script: xcode-project use-profiles

      - name: Install melos
        script: dart pub global activate melos

      - name: Bootstrap repository
        script: melos bootstrap

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
           --build-name=${CM_TAG/#enmeshed-v/} \
           --export-options-plist=/Users/builder/export_options.plist \
           --dart-define="app_baseUrl=$app_baseUrl" \
           --dart-define="app_clientId=$app_clientId" \
           --dart-define="app_clientSecret=$app_clientSecret"
        working_directory: apps/enmeshed

      - name: Build finished successfully
        script: touch ~/SUCCESS

    artifacts:
      - apps/enmeshed/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - apps/enmeshed/flutter_drive.log